export const INSERT_BUFFERS = "db/INSERT_BUFFERS";
export const INSERT_REPORTS = "db/INSERT_REPORTS";

export const INSERT_COMMAND = "db/INSERT_COMMAND";
export const INSERT_RESPONSE = "db/INSERT_RESPONSE";
