export const INSERT_RESPONSES = "INSERT_RESPONSES";
export const INSERT_REPORTS = "INSERT_REPORTS";
export const INSERT_COMMAND = "INSERT_COMMAND";
export const STOP_COMMAND = "STOP_COMMAND";

export const INSERT_DEVICES = "INSERT_DEVICES";
