export const SET_LOADING = "SET_LOADING";
export const TOGGLE_CALIBRATION = "TOGGLE_CALIBRATION";
export const TOGGLE_DARKER = "TOGGLE_DARKER";
export const CLEAR_ALL = "CLEAR_ALL";

export const SET_THE_UNIT = "SET_THE_UNIT";
export const SET_THE_REPORT = "SET_THE_REPORT";
export const SET_COMMAND_BUFFER = "SET_COMMAND_BUFFER";
export const CLEAR_COMMAND_BUFFER = "CLEAR_COMMAND_BUFFER";
export const SET_THE_COMMAND = "SET_THE_COMMAND";
export const CLEAR_THE_COMMAND = "CLEAR_THE_COMMAND";

export const ADD_UNITS = "ADD_UNITS";
export const ADD_REPORTS = "ADD_REPORTS";
export const ADD_COMMANDS = "ADD_COMMANDS";

export const ADD_FINGERS = "ADD_FINGERS";
export const DELETE_FINGERS = "DELETE_FINGERS";
export const RESET_FINGERS = "RESET_FINGERS";
